### ISSUE TITLE
0.24 regression, `#[darling(with = ...)]` requires `FromMeta` impl

### ISSUE THREAD

**Issue by Veetaha** [TedDriggs/darling#433]
This compiles on 0.23 but not on 0.24:

```rust
use darling::FromMeta;

#[derive(Default)]
struct NotFromMeta;

fn parser(_meta: &syn::Meta) -> darling::Result<NotFromMeta> {
    Ok(NotFromMeta)
}

#[derive(FromMeta)]
struct Opts {
    #[darling(default, with = parser)]
    field: NotFromMeta,
}
```

Output:
```
error[E0277]: the trait bound `NotFromMeta: darling::FromMeta` is not satisfied
  --> crates/sandbox/src/main.rs:12:31
   |
12 |     #[darling(default, with = parser)]
   |                               ^^^^^^ unsatisfied trait bound
   |
```

**Comment by TedDriggs** [comment]
Oof, thanks for reporting. I wonder why that's happening... I have a hunch that it's to do with `from_none`.

**Comment by TedDriggs** [comment]
~@nik-rev I am looking over the code here, and am not yet seeing the regression. I know we do some tricks to make `from_none` work... any ideas on where the issue is coming from?~

~I should do `git bisect` on this, but haven't had time yet.~

@flisky has identified the cause of the regression and put up a PR.

**Comment by TedDriggs** [comment]
Fixed in [v0.24.1](https://github.com/TedDriggs/darling/releases/tag/v0.24.1)
