### ISSUE TITLE
Some kind of semver violation in 0.20.11

### ISSUE THREAD

**Issue by anlumo** [TedDriggs/darling#333]
The crate serde\_columnar doesn't compile with darling 0.20.11, but works fine with 0.20.10.

Note: I'm not the author of that crate, but I'm using a dependency that uses columnar (yes, I had to dig in four levels deep to get here).

Steps:

```bash
git clone https://github.com/loro-dev/columnar.git
cd columnar/
cargo update # just to make sure to grab 0.20.11
cargo check
```

Error output:

```
   Compiling serde_columnar_derive v0.3.5 (/home/anlumo/Documents/dungeonfog/columnar/columnar_derive)
error[E0433]: failed to resolve: you might be missing crate `core`
  --> columnar_derive/src/args.rs:35:9
   |
35 |     pub attrs: Vec<syn::Attribute>,
   |         ^^^^^ you might be missing crate `core`

error[E0433]: failed to resolve: you might be missing crate `core`
  --> columnar_derive/src/args.rs:60:9
   |
60 |     pub attrs: Vec<syn::Attribute>,
   |         ^^^^^ you might be missing crate `core`

warning: unexpected `cfg` condition name: `exhaustive`
   --> columnar_derive/src/args.rs:452:30
    |
452 |         #[cfg_attr(all(test, exhaustive), deny(non_exhaustive_omitted_patterns))]
    |                              ^^^^^^^^^^
    |
    = help: expected names are: `docsrs`, `feature`, and `test` and 31 more
    = help: consider using a Cargo feature instead
    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
             [lints.rust]
             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(exhaustive)'] }
    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(exhaustive)");` to the top of the `build.rs`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: `#[warn(unexpected_cfgs)]` on by default

error[E0599]: no function or associated item named `from_field` found for struct `FieldArgs` in the current scope
   --> columnar_derive/src/args.rs:333:45
    |
29  | pub struct FieldArgs {
    | -------------------- function or associated item `from_field` not found for this struct
...
333 |                 let field_args = FieldArgs::from_field(field)?;
    |                                             ^^^^^^^^^^ function or associated item not found in `FieldArgs`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `from_field`, perhaps you need to implement it:
            candidate #1: `FromField`

error[E0599]: no function or associated item named `from_field` found for struct `FieldArgs` in the current scope
  --> columnar_derive/src/ast.rs:21:31
   |
21 |         let args = FieldArgs::from_field(field)?;
   |                               ^^^^^^^^^^ function or associated item not found in `FieldArgs`
   |
  ::: columnar_derive/src/args.rs:29:1
   |
29 | pub struct FieldArgs {
   | -------------------- function or associated item `from_field` not found for this struct
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `from_field`, perhaps you need to implement it:
           candidate #1: `FromField`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
```

Then change `columnar_derive/Cargo.toml` from

```toml
darling = "0.20.10"
```

to

```toml
darling = "=0.20.10"
```

Then check again

```bash
cargo check
```

Works fine.

That error message "you might be missing crate `core`" is wild, I can't find any reference to it existing on the Web, and it also doesn't make sense. core is always included.

**Comment by TedDriggs** [comment]
Hmm - the presence of this piece makes me suspicious about whether there's something going on in columnar_derive that's causing the problem:

```
warning: unexpected `cfg` condition name: `exhaustive`
```

I'm not sure what that cfg is, but it does sound like something that might be causing derive failure?

**Comment by NickCaplinger** [comment]
Defining an explicit Rust edition (i.e. not implicitly defaulting to "2015") in `columnar_derive` gives a more descriptive error:
```
error: field will not be populated because `forward_attrs` is not set on the struct
  --> columnar_derive\src\args.rs:35:9
   |
35 |     pub attrs: Vec<syn::Attribute>,
   |         ^^^^^

error: field will not be populated because `forward_attrs` is not set on the struct
  --> columnar_derive\src\args.rs:60:9
   |
60 |     pub attrs: Vec<syn::Attribute>,
   |         ^^^^^
```

Perhaps fa552e4f is related?

**Comment by TedDriggs** [comment]
@NickCaplinger spot on. It does seem like a bug in that crate at first glance; I can't see where the field is being set to anything but the default value (an empty array)

**Comment by anlumo** [comment]
Could you file a ticket on that project for this? I’d do it, but I don’t think that I could explain it properly.

**Comment by Leeeon233** [comment]
Hello there! As the author of `serde_columnar`, I'd like to thank you for spotting this issue. I've fixed that in the latest version, so I believe we can close this issue now.
